# Generated by Django 4.0.6 on 2023-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='basket',
            field=models.ManyToManyField(blank=True, to='users.stock'),
        ),
    ]
