# Generated by Django 4.0.6 on 2023-08-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_market_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='supervisor',
            field=models.ManyToManyField(related_name='supervisor_seller_set', to='users.market'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='markets',
            field=models.ManyToManyField(related_name='markets_seller_set', to='users.market'),
        ),
    ]
