# Generated by Django 4.0.6 on 2023-09-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_stock_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stock', models.IntegerField()),
                ('date_placed', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(300, 'Pending'), (200, 'Delivered'), (403, 'Declined')])),
                ('message', models.CharField(max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.market')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.stock')),
            ],
        ),
    ]
