# Generated by Django 4.0.6 on 2023-08-25 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_market_is_active_alter_customer_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='rate',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
