# Generated by Django 4.0.6 on 2023-08-25 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seller_supervisor_alter_seller_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
