# Generated by Django 4.0.6 on 2023-09-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_stock_ppg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.market'),
        ),
    ]
